/** Fun facts shown while Cosmo "thinks up" a new question, so waiting feels like learning. */
export const MATH_TRIVIA: string[] = [
  "The equals sign (=) was invented in 1557 by Robert Recorde, who was tired of writing 'is equal to' over and over.",
  'Ada Lovelace wrote notes in the 1840s describing how a machine could follow step-by-step instructions, making her the first computer programmer ever.',
  'Carl Friedrich Gauss supposedly added up 1 to 100 in seconds as a kid by pairing numbers: (1+100) + (2+99) + ... = 101 x 50.',
  "Honeybees build honeycombs out of hexagons because that shape stores the most honey using the least wax — nature loves efficient math!",
  'The Fibonacci sequence (1, 1, 2, 3, 5, 8, 13...) shows up in sunflower seeds, pinecones, and even the spiral arms of galaxies.',
  "Al-Khwarizmi, a 9th-century Persian scholar, wrote a book whose title gave us the word 'algebra'.",
  'Zero was not always a number. Ancient Rome had no symbol for it at all, and it took centuries for zero to be accepted as a real number.',
  "Hypatia of Alexandria, who lived around 350-415 AD, was one of the first women known to make major contributions to mathematics and astronomy.",
  'GPS satellites have to correct their clocks using Einstein\'s equations of relativity — without that math, your map app could be off by miles!',
  'Srinivasa Ramanujan taught himself advanced math from library books in India and discovered thousands of new formulas with almost no formal training.',
  "Katherine Johnson's hand calculations helped NASA plot the flight paths that sent astronauts to orbit and back safely.",
  'Pierre de Fermat once scribbled a math claim in the margin of a book — it took mathematicians 358 years to finally prove it.',
  'Music and math are close friends: jumping up one octave means doubling the sound wave frequency, a simple 2:1 ratio.',
  "Online shopping is kept safe by cryptography that relies on how hard it is to factor extremely large numbers — a problem straight out of algebra class.",
  'Johannes Kepler discovered that planets travel around the Sun in ellipses, not perfect circles, using nothing but careful math and observation.',
  'To escape Earth\'s gravity, a rocket needs to reach about 11.2 kilometers per second — that speed comes straight from algebra and physics equations.',
  'Emmy Noether proved a theorem connecting symmetry to the conservation of energy, becoming one of the most influential mathematicians in physics.',
  "Negative numbers were once considered 'absurd' by many mathematicians — it took hundreds of years for them to be fully accepted.",
  "Pythagoras and his followers were so fascinated by numbers that they formed a secret society built around mathematical ideas.",
  "Euclid's book 'Elements,' written over 2,000 years ago, is still one of the most influential math textbooks in history.",
  'Architects and engineers use quadratic equations to design arches and bridges that can safely hold their shape under weight.',
  'Weather forecasters use systems of equations and huge amounts of data to predict whether it will rain tomorrow.',
  'The word "algorithm" — a set of step-by-step instructions — comes from the name of the mathematician Al-Khwarizmi.',
  'Video game graphics rely on functions and coordinate geometry to figure out exactly where every pixel and character should appear on screen.',
];

/** Fun facts shown while Cosmo "thinks up" a new biology question. */
export const BIOLOGY_TRIVIA: string[] = [
  'A single teaspoon of soil can contain more living microorganisms than there are people on Earth.',
  "Octopuses have three hearts and blue blood — their blood uses copper instead of iron to carry oxygen.",
  'Your body replaces most of its cells on a regular basis — red blood cells live about four months before being recycled.',
  "Tardigrades ('water bears') can survive being frozen, dried out completely, and even exposed to the vacuum of space.",
  "Bananas share about 60% of their DNA with humans, a reminder that all life shares a common evolutionary history.",
  'The human body contains around 37 trillion cells, each one carrying nearly the same set of DNA instructions.',
  "If you stretched out all the DNA in one of your cells, it would be about 2 meters long — yet it fits inside a nucleus too small to see.",
  'Some jellyfish, like Turritopsis dohrnii, can reverse their aging process and essentially become young again.',
  "Photosynthesis in plants and algae produces most of the oxygen we breathe — even some ocean plankton play a huge role.",
  'Mitochondria, the "powerhouses" of cells, were once free-living bacteria that were absorbed by ancient cells billions of years ago.',
  'A group of crows is called a "murder," but crows are also famously intelligent and can recognize individual human faces.',
  "The axolotl, a type of salamander, can regrow entire limbs, parts of its heart, and even sections of its brain.",
  "Humans share about 98-99% of their DNA with chimpanzees, our closest living relatives.",
  'Sharks have been around for over 400 million years — longer than trees have existed on Earth.',
  "A bolt of lightning can trigger chemical reactions in the atmosphere that mimic the early steps scientists think led to life's building blocks.",
  'Some bacteria can go dormant for thousands of years and then "wake up" and start growing again when conditions improve.',
  "Your stomach lining replaces itself every few days — otherwise the acid that digests your food would start digesting your stomach.",
  'Mushrooms are more closely related to animals than to plants on the tree of life.',
  "The Venus flytrap counts: it only snaps shut after its trigger hairs are touched twice within about 20 seconds, to avoid wasting energy on false alarms.",
  "Elephants are one of the few animals that can recognize themselves in a mirror, a sign of self-awareness.",
  'A single strand of spider silk is stronger than a steel wire of the same thickness.',
  "Cells called neurons can be over a meter long in large animals — a single neuron can stretch from your spine to your toes.",
  "Some species of frogs can survive being frozen solid in winter, then thaw out and hop away in spring.",
  'The platypus is one of the only mammals that lays eggs instead of giving birth to live young.',
];

/** Fun facts shown while Cosmo "thinks up" a new Python question. */
export const PYTHON_TRIVIA: string[] = [
  'Python was created by Guido van Rossum and first released in 1991 — he named it after the comedy group Monty Python, not the snake.',
  "Python's official style guide, PEP 8, says code is read much more often than it's written — which is why naming and formatting matter so much.",
  'The famous Zen of Python ("Beautiful is better than ugly", "Simple is better than complex") can be read anytime by typing `import this`.',
  'Python uses indentation instead of curly braces to define code blocks — whitespace is actually part of the syntax.',
  "Lists in Python are dynamic arrays: they can grow or shrink, and can even hold mixed types like numbers, strings, and other lists.",
  'Python dictionaries have kept insertion order since Python 3.7 — before that, the order was not guaranteed.',
  'The print() function used to be a statement in Python 2; Python 3 made it a regular function, which is why you now write print("hi") with parentheses.',
  'Instagram, Spotify, and YouTube have all relied heavily on Python in their backend systems.',
  'NASA has used Python for everything from analyzing data to scripting tools used by mission engineers.',
  "Python's built-in range() doesn't create a full list in memory — it generates numbers one at a time, which saves memory for big loops.",
  'A Python "duck" is not a bird: "duck typing" means Python cares about what an object can do, not what class it belongs to — if it walks like a duck and quacks like a duck...',
  'The // operator in Python performs floor division — 7 // 2 gives 3, not 3.5.',
  'Python lets you swap two variables in one line: a, b = b, a — no temporary variable needed.',
  'List comprehensions were inspired by set-builder notation in mathematics, like {x^2 : x in naturals}.',
  'Every Python script file is automatically called a "module," and a folder of modules with an __init__.py file becomes a "package."',
  'f-strings, written like f"Hello {name}", were added in Python 3.6 and are now the most common way to format text.',
  "Python's None is a singleton — there is only ever one None object in a running program, no matter how many times you write it.",
  'The Python Package Index (PyPI) hosts hundreds of thousands of free packages you can install with pip install.',
  'Booleans in Python are actually a subclass of integers — True equals 1 and False equals 0 under the hood.',
  'Generators let Python produce values one at a time using yield, which is why they can represent infinite sequences without running out of memory.',
  'The walrus operator := , added in Python 3.8, lets you assign a value to a variable as part of a larger expression.',
  "Python's try/except blocks can also include an else clause, which runs only if no exception was raised.",
  'Type hints in Python (like "def add(a: int, b: int) -> int:") are optional and not enforced at runtime — they exist mainly to help tools and humans.',
  'A single underscore _ is often used in Python as a throwaway variable name for values you plan to ignore.',
];

/** Fun facts shown while Cosmo "thinks up" a new robotics question. */
export const ROBOTICS_TRIVIA: string[] = [
  "The word 'robot' comes from the Czech word 'robota,' meaning forced labor — it first appeared in a 1920 play by Karel Capek.",
  'NASA\'s Mars rovers, like Curiosity and Perseverance, are essentially giant robots that can drive, dig, and analyze rocks millions of miles from Earth.',
  'A robot needs three basic things to work: sensors to gather information, a "brain" to decide what to do, and actuators to act on that decision.',
  'The Roomba vacuum robot uses simple sensors to detect walls and furniture, then bounces around the room in patterns until it has cleaned everything.',
  'Some robotic arms in factories can move with precision down to a fraction of a millimeter, far more accurate than a human hand.',
  'Boston Dynamics\' robot "Spot" uses gyroscopes and force sensors in its legs to balance itself, even on uneven ground.',
  'The first industrial robot, called Unimate, started working on a General Motors assembly line in 1961, lifting and stacking hot metal parts.',
  'A servo motor can rotate to a specific angle and hold it there, which is why they are used to steer wheels and move robotic arm joints.',
  'Many robots use a sensor called a "gyroscope" to sense rotation, the same kind of sensor that helps your phone know which way is up.',
  'Closed-loop control means a robot checks its own results and adjusts — like a thermostat that turns the heater on and off to stay at the right temperature.',
  'A PID controller — used in everything from drones to self-driving cars — constantly nudges a system based on how far off it currently is, how long it has been off, and how fast the error is changing.',
  'Some underwater exploration robots can dive deeper than any human diver, surviving crushing pressure to map shipwrecks and ocean trenches.',
  'A robot\'s "degrees of freedom" describe the number of independent ways it can move — a human arm has about 7, while many robot arms have 6.',
  'Line-following robots often use simple light sensors to detect a dark line on a light floor, steering left or right to stay on track.',
  'The Mars rover Perseverance carries a tiny helicopter named Ingenuity, the first aircraft to achieve powered flight on another planet.',
  'Some robots are "soft robots" made from flexible, squishy materials inspired by octopuses, letting them squeeze through tight spaces.',
  'Robotic exoskeletons can help people who have lost the use of their legs to stand and walk again by amplifying their movements.',
  'A breadboard lets you build and test electronic circuits without soldering, which is why it\'s a favorite tool for robotics beginners.',
  'Arduino boards, first released in 2005, made it cheap and easy for students and hobbyists to build their own robots and gadgets.',
  'Many warehouse robots, like those used by large shipping companies, navigate using grids of barcodes on the floor instead of cameras.',
  'A robot vacuum that "remembers" your house is usually building an internal map using a technique called SLAM (Simultaneous Localization and Mapping).',
  'Some robots use machine learning to get better at tasks over time, the same way you improve at a video game the more you practice.',
  'Engineers test robot safety extensively because a robot arm moving at factory speed can be dangerous if it doesn\'t sense a person nearby.',
  'Honda\'s ASIMO robot, one of the most famous humanoid robots, could walk, run, climb stairs, and even recognize faces and voices.',
];

/** Fun facts shown while Cosmo "thinks up" a new space science question. */
export const SPACE_TRIVIA: string[] = [
  'A day on Venus is longer than its year — Venus takes 243 Earth days to rotate once, but only 225 Earth days to orbit the Sun.',
  "Neutron stars can spin hundreds of times per second — some 'pulsars' rotate faster than a kitchen blender.",
  'The footprints astronauts left on the Moon could last millions of years, since there is no wind or water to erode them.',
  "Saturn's rings are made mostly of ice chunks, some as small as dust grains and others as large as mountains.",
  'One million Earths could fit inside the Sun, and the Sun itself is considered an average-sized star.',
  "Light from the Sun takes about 8 minutes to reach Earth, so we always see the Sun as it looked 8 minutes ago.",
  "The largest known star, UY Scuti, is so big that if it replaced the Sun, its surface would extend past Jupiter's orbit.",
  'Space is completely silent because sound waves need a medium like air or water to travel through, and space is a near-perfect vacuum.',
  "Olympus Mons on Mars is the largest volcano in the solar system — about 2.5 times taller than Mount Everest.",
  "A spoonful of material from a neutron star would weigh about a billion tons on Earth.",
  'The Great Red Spot on Jupiter is a giant storm that has been raging for at least 350 years and is larger than Earth.',
  "Astronauts can grow up to 5 centimeters taller in space because microgravity lets the spine stretch out.",
  'Halley\'s Comet returns to the inner solar system roughly every 76 years and was last seen in 1986.',
  "The Voyager 1 spacecraft, launched in 1977, is now the most distant human-made object, traveling in interstellar space.",
  'There is a planet made largely of diamond-like material, with a mass and radius slightly larger than Earth, called 55 Cancri e.',
  "The footprints of the asteroid belt total less mass than our Moon, even though it contains millions of rocky objects.",
  'Jupiter has at least 95 known moons, including Ganymede, which is larger than the planet Mercury.',
  "A 'shooting star' isn't a star at all — it's a small piece of rock or dust burning up as it enters Earth's atmosphere.",
  'The International Space Station travels at about 28,000 km/h, orbiting Earth roughly every 90 minutes.',
  "Black holes don't actually 'suck' things in — objects can orbit them safely as long as they stay outside the event horizon.",
  'The coldest known place in the universe naturally is the Boomerang Nebula, at about -272°C, just above absolute zero.',
  "Mercury and Venus are the only planets in our solar system with no moons.",
  'The Hubble Space Telescope has been operating for over 30 years and has helped measure the age of the universe at about 13.8 billion years.',
  "If you could drive a car at highway speed to the Sun, it would take over 160 years to get there.",
];

/** Fun facts shown while Cosmo "thinks up" a new physics question. */
export const PHYSICS_TRIVIA: string[] = [
  "Newton published his three laws of motion in Principia Mathematica in 1687 — at the request of astronomer Edmond Halley, who also paid for the printing.",
  "Einstein developed the theory of special relativity at age 26, while working as a patent clerk in Bern, Switzerland.",
  "The speed of light in a vacuum is approximately 299,792,458 m/s — fast enough to circle Earth 7.5 times every second.",
  "In a vacuum, all objects fall at the same rate regardless of mass. Galileo is said to have proved this by dropping balls from the Leaning Tower of Pisa.",
  "GPS satellites must apply corrections from both special and general relativity — without them, your GPS position would drift by miles per day.",
  "Marie Curie was the first person to win Nobel Prizes in two different sciences: Physics in 1903 and Chemistry in 1911.",
  "Sound travels roughly 4 times faster through water than through air, which is why sonar is so effective underwater.",
  "Superconductors conduct electricity with zero resistance, but only at extremely low temperatures — some near absolute zero (−273°C).",
  "The Large Hadron Collider at CERN accelerates protons to 99.9999991% of the speed of light.",
  "The photoelectric effect, explained by Einstein in 1905, showed that light comes in discrete packets called photons — this insight won him the Nobel Prize.",
  "Nuclear fission of just 1 kg of uranium-235 releases as much energy as burning about 3,000 tons of coal.",
  "The Tacoma Narrows Bridge collapsed in 1940 because wind drove the bridge into resonance — a dramatic real-world physics lesson.",
  "James Clerk Maxwell unified electricity and magnetism in the 1860s, predicting that light itself is an electromagnetic wave.",
  "Nikola Tesla and Thomas Edison famously battled over AC vs DC electricity. AC won, and is the standard that powers homes today.",
  "Entropy from thermodynamics explains why heat naturally flows from hot to cold — and why perpetual motion machines are impossible.",
  "The Higgs boson, discovered at CERN in 2012, explains why fundamental particles have mass. Its field permeates all of space.",
  "Lasers work by stimulating atoms to emit photons all in the same phase. LASER stands for Light Amplification by Stimulated Emission of Radiation.",
  "Fiber optic cables transmit internet data as pulses of light, kept inside the glass fiber by total internal reflection.",
  "Semiconductors like silicon are the backbone of all modern electronics — the transistors in your phone number in the billions.",
  "The double-slit experiment shows electrons behave like waves when unobserved and like particles when measured — one of the strangest results in science.",
  "Richard Feynman's path integral formulation of quantum mechanics calculates every possible path a particle could take and sums them all up.",
  "A neutron star is so dense that a teaspoon of its material would weigh about a billion tons on Earth.",
  "Airbags reduce injury by increasing the collision time, which reduces the force on passengers — a direct application of the impulse-momentum theorem.",
  "The aurora borealis (Northern Lights) is caused by charged solar wind particles following Earth's magnetic field lines into the atmosphere.",
];

/** Fun facts shown while Cosmo "thinks up" a new hackathon question. */
export const CHEMISTRY_TRIVIA: string[] = [
  "There are more possible arrangements of atoms in a single grain of sand than there are stars in the observable universe.",
  "Water is one of the only substances that expands when it freezes — which is why ice floats and lakes freeze from the top down, protecting aquatic life.",
  "The human body contains about 7 octillion (7 × 10²⁷) atoms — mostly hydrogen, oxygen, and carbon.",
  "Gold is so chemically unreactive that archaeologists have found 3,000-year-old gold artifacts that still look brand new.",
  "Sodium explodes on contact with water, yet sodium and chlorine combine to make table salt — one of the most essential substances in human life.",
  "A single teaspoon of neutron star material contains more atoms than all the sand on Earth — achieved because nuclear forces compress matter to extreme density.",
  "Gallium metal melts at just 29.8°C (85.6°F) — meaning it melts in the palm of your hand from body heat alone.",
  "The most abundant element in the universe by mass is hydrogen — it makes up about 75% of all normal matter.",
  "Ozone (O₃) absorbs harmful UV radiation in the stratosphere, but the same ozone at ground level is a pollutant that irritates lungs.",
  "Diamonds and graphite are both made entirely of carbon — the difference is only the arrangement of atoms (crystal lattice vs. layered sheets).",
  "Chlorophyll in plants absorbs red and blue light for photosynthesis but reflects green — which is why almost all plants look green to us.",
  "The pH scale is logarithmic: a solution with pH 4 is 10 times more acidic than pH 5, and 100 times more acidic than pH 6.",
  "Rust (iron oxide) is not just dirty iron — it's a different substance with a completely different chemical formula (Fe₂O₃) created by a reaction with oxygen and water.",
  "Helium is the only element that was discovered on the Sun before it was found on Earth — its spectral lines were spotted in sunlight in 1868.",
  "Catalysts speed up chemical reactions without being consumed themselves — enzymes in your body are biological catalysts that run millions of reactions per second.",
  "The smell of rain on dry earth is caused by a chemical called petrichor — produced when rainwater disturbs oils secreted by soil bacteria called actinomycetes.",
  "Hydrogen bonds between water molecules give water a surprisingly high boiling point — without them, water would boil at −80°C and life as we know it would be impossible.",
  "Baking soda (NaHCO₃) reacts with vinegar (acetic acid) to produce CO₂ gas — the same reaction that makes cakes rise in the oven.",
  "The element mercury is liquid at room temperature — one of only two elements (along with bromine) that are liquid under standard conditions.",
  "Antibiotics work by targeting chemical processes unique to bacterial cells, leaving human cells unharmed — a concept called selective toxicity.",
  "The Haber-Bosch process, which synthesizes ammonia from nitrogen and hydrogen, is estimated to enable the food production needed to feed about half the world's current population.",
  "Alloys like steel (iron + carbon) and bronze (copper + tin) often have completely different properties from their component metals — mixing can create strength neither element has alone.",
  "Carbon has four bonding sites, which lets it form long chains, rings, and branching structures — making millions of different organic compounds possible.",
  "Soap works because one end of a soap molecule loves water (hydrophilic) and the other end loves oil (hydrophobic) — trapping grease in a bubble that rinses away.",
];

export const HACKATHON_TRIVIA: string[] = [
  "The word 'hackathon' blends 'hack' (creative problem-solving) and 'marathon' — the first widely documented event was a 1999 Sun Microsystems OpenBSD sprint.",
  "Mark Zuckerberg ran regular hackathons at Facebook — the Like button, Facebook Chat, and Timeline all started as hackathon projects.",
  "Major League Hacking (MLH) sanctions over 200 hackathons per year worldwide, with tens of thousands of student participants across more than 100 countries.",
  "The average hackathon lasts 24 to 48 hours, but some 'sprint' events run as short as 4 hours — proving you don't need a weekend to build something real.",
  "Groupon, the billion-dollar coupon company, was originally built as a hackathon side project called 'The Point' in a single weekend.",
  "NASA hosts its own hackathon called the International Space Apps Challenge — open to anyone, it's one of the largest hackathons on Earth with thousands of teams globally.",
  "The GitHub Student Developer Pack gives students free access to over 100 developer tools worth thousands of dollars — many top hackers use it to build their first real projects.",
  "Hackathon teams that write down their problem statement in the first 15 minutes consistently outperform teams that jump straight to coding, according to mentors who've seen hundreds of events.",
  "The winning project at many hackathons is rarely the most technically complex — it's the one that solves a real problem most clearly and demos without crashing.",
  "Angel investor and Y Combinator founder Paul Graham coined the phrase 'Make something people want' — which is also the best single rule for picking a hackathon idea.",
  "Many hackathon organizers say the teams that talk to potential users before building — even just texting a friend who has the problem — win more consistently than those who don't.",
  "The average age of first-time hackathon participants has been dropping every year — today, many events see participants as young as 13 or 14 competing seriously.",
  "Devpost, the largest hackathon platform, has hosted submissions from over 1.5 million developers across thousands of events since it launched.",
  "Imposter syndrome — feeling like you don't belong or aren't good enough — is reported by the majority of first-time hackathon attendees. Most say it disappeared by hour 6.",
  "Some of the most successful hackathon projects were built by teams whose members had never met before the event — forming a team of strangers at the door is a completely normal and often rewarding experience.",
  "The pitch is often weighted as heavily as the technical project by judges — a team with a clear, confident 3-minute story regularly beats more technically polished teams who can't explain their idea.",
  "Sleep is a genuine competitive advantage at long hackathons. Studies on decision-making show that teams who take even a 2-hour rest mid-event make better scoping decisions than those who code through the night.",
  "Many hackathon sponsors actively recruit participants during events — bringing a resume or LinkedIn profile is not unusual and has led to internships and job offers.",
  "The best hackathon README files follow a simple formula: what problem it solves, who it's for, how to run it, and what you'd build next. Writing it before you start helps clarify the idea.",
  "Replit, GitHub Codespaces, and similar cloud IDEs mean you can now start coding at a hackathon with zero local setup — a huge advantage for beginners who used to lose hours configuring environments.",
  "The 'rubber duck debugging' technique — explaining your code to an inanimate object to find bugs — was invented by a programmer but is now standard mentor advice at hackathons when you're stuck.",
  "'Ship it' culture, popular in Silicon Valley and at hackathons, is the belief that a done project you can share beats a perfect project that never ships — done is better than perfect.",
  "Many high school hackathon alumni go on to win college competitions, start companies, and land top tech internships — the skills stack, and the earlier you start the bigger your advantage.",
  "The hackathon format was inspired by open source 'sprints' where developers gather to rapidly add features to a project — the competitive twist was added later to drive urgency and innovation.",
];

/** Pick a random trivia fact from a list, optionally avoiding the most recently shown one. */
export function randomTrivia(list: string[], exclude?: string): string {
  if (list.length <= 1) return list[0];
  let pick: string;
  do {
    pick = list[Math.floor(Math.random() * list.length)];
  } while (pick === exclude);
  return pick;
}
